use soroban_sdk::{
    contract, contractclient, contracterror, contractimpl, contracttype, panic_with_error,
    symbol_short, token, Address, Env, String, Vec,
};

const DAY_IN_LEDGERS: u32 = 17280;
const BUMP_AMOUNT: u32 = 365 * DAY_IN_LEDGERS;
const LIFETIME_THRESHOLD: u32 = BUMP_AMOUNT - 30 * DAY_IN_LEDGERS;
const MAX_CLAIM_MANY: u32 = 20;

/// The snapshot surface every Ankara fungible template exposes (see
/// `ankara_common::fungible::snapshot`).
#[contractclient(name = "SnapshotTokenClient")]
pub trait SnapshotToken {
    fn snapshot(env: Env) -> u32;
    fn balance_of_at(env: Env, id: Address, snapshot_id: u32) -> i128;
    fn total_supply_at(env: Env, snapshot_id: u32) -> i128;
}

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum DistributorError {
    InvalidAmount = 1,
    NoSupply = 2,
    DistributionNotFound = 3,
    AlreadyClaimed = 4,
    NothingToClaim = 5,
    ClaimWindowClosed = 6,
    ClaimWindowOpen = 7,
    NotCreator = 8,
    TooMany = 9,
}

#[contracttype]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Distribution {
    pub id: u64,
    /// The RWA token whose holders are paid.
    pub asset_token: Address,
    /// What they're paid in (e.g. a USDC SAC).
    pub payout_token: Address,
    pub snapshot_id: u32,
    pub total_amount: i128,
    pub supply_at_snapshot: i128,
    pub claimed_amount: i128,
    pub creator: Address,
    pub created_at: u64,
    /// `0` = holders can claim forever; otherwise the creator may reclaim
    /// what's left after this timestamp.
    pub claim_deadline: u64,
    pub reclaimed: bool,
    /// Free-form label, e.g. "Rent Q3 2026" or "Royalty Aug 2026".
    pub memo: String,
}

#[contracttype]
enum DataKey {
    NextId,
    Distribution(u64),
    Claimed(u64, Address),
    ByToken(Address),
}

/// Pays income generated by an asset (rent, royalties, coupon, harvest
/// proceeds) to the holders of its RWA token, pro-rata to their balance at
/// a snapshot — the on-chain half of `declare_rental_distribution` /
/// `declare_royalty`, which only record the amount.
///
/// Flow: the token's Manager calls `create_distribution` — this takes a
/// balance snapshot on the token (requires the token's Manager auth, so
/// only the issuer can distribute) and pulls `amount` of the payout token
/// into escrow. Each holder then `claim`s `amount * balance_at_snapshot /
/// supply_at_snapshot`. Recurring payouts are just one distribution per
/// period.
///
/// Balances held by contracts that can't call `claim` (an RFQ escrow, a
/// pool) are left unclaimed; with a `claim_deadline`, the creator can
/// `reclaim` the remainder afterwards.
///
/// Singleton, no admin; works with any Ankara fungible template.
#[contract]
pub struct RevenueDistributor;

#[contractimpl]
impl RevenueDistributor {
    pub fn create_distribution(
        env: Env,
        creator: Address,
        asset_token: Address,
        payout_token: Address,
        amount: i128,
        claim_window_secs: u64,
        memo: String,
    ) -> u64 {
        creator.require_auth();
        if amount <= 0 {
            panic_with_error!(&env, DistributorError::InvalidAmount);
        }
        let asset = SnapshotTokenClient::new(&env, &asset_token);
        let snapshot_id = asset.snapshot();
        let supply = asset.total_supply_at(&snapshot_id);
        if supply <= 0 {
            panic_with_error!(&env, DistributorError::NoSupply);
        }

        let id: u64 = env.storage().instance().get(&DataKey::NextId).unwrap_or(0);
        env.storage().instance().set(&DataKey::NextId, &(id + 1));
        let now = env.ledger().timestamp();
        let d = Distribution {
            id,
            asset_token: asset_token.clone(),
            payout_token: payout_token.clone(),
            snapshot_id,
            total_amount: amount,
            supply_at_snapshot: supply,
            claimed_amount: 0,
            creator: creator.clone(),
            created_at: now,
            claim_deadline: if claim_window_secs == 0 { 0 } else { now + claim_window_secs },
            reclaimed: false,
            memo,
        };
        write(&env, &d);

        let by_key = DataKey::ByToken(asset_token.clone());
        let mut ids: Vec<u64> = env
            .storage()
            .persistent()
            .get(&by_key)
            .unwrap_or_else(|| Vec::new(&env));
        ids.push_back(id);
        env.storage().persistent().set(&by_key, &ids);
        env.storage()
            .persistent()
            .extend_ttl(&by_key, LIFETIME_THRESHOLD, BUMP_AMOUNT);

        token::TokenClient::new(&env, &payout_token).transfer(
            &creator,
            &env.current_contract_address(),
            &amount,
        );
        env.events().publish(
            (symbol_short!("dist_new"), asset_token, id),
            (payout_token, amount, snapshot_id),
        );
        id
    }

    /// Pays `holder` their share of distribution `id`. Returns the amount.
    pub fn claim(env: Env, holder: Address, distribution_id: u64) -> i128 {
        holder.require_auth();
        claim_one(&env, &holder, distribution_id)
    }

    /// Claims several distributions at once (max 20), skipping ones with
    /// nothing owed or already claimed. Returns the total paid.
    pub fn claim_many(env: Env, holder: Address, distribution_ids: Vec<u64>) -> i128 {
        holder.require_auth();
        if distribution_ids.len() > MAX_CLAIM_MANY {
            panic_with_error!(&env, DistributorError::TooMany);
        }
        let mut total = 0;
        for id in distribution_ids.iter() {
            let d = read(&env, id);
            if is_claimed(&env, id, &holder) || share_of(&env, &d, &holder) == 0 || window_closed(&env, &d) {
                continue;
            }
            total += claim_one(&env, &holder, id);
        }
        total
    }

    /// After the claim deadline, returns everything unclaimed to the
    /// creator. Distributions with no deadline can't be reclaimed.
    pub fn reclaim(env: Env, creator: Address, distribution_id: u64) -> i128 {
        creator.require_auth();
        let mut d = read(&env, distribution_id);
        if d.creator != creator {
            panic_with_error!(&env, DistributorError::NotCreator);
        }
        if d.claim_deadline == 0 || env.ledger().timestamp() <= d.claim_deadline {
            panic_with_error!(&env, DistributorError::ClaimWindowOpen);
        }
        if d.reclaimed {
            panic_with_error!(&env, DistributorError::NothingToClaim);
        }
        let remainder = d.total_amount - d.claimed_amount;
        d.reclaimed = true;
        write(&env, &d);
        if remainder > 0 {
            token::TokenClient::new(&env, &d.payout_token).transfer(
                &env.current_contract_address(),
                &creator,
                &remainder,
            );
        }
        env.events()
            .publish((symbol_short!("reclaim"), distribution_id), remainder);
        remainder
    }

    // ─── Reads ───────────────────────────────────────────────────────────

    pub fn get_distribution(env: Env, distribution_id: u64) -> Distribution {
        read(&env, distribution_id)
    }

    /// What `holder` could claim now (0 if claimed, window closed, or no
    /// balance at the snapshot).
    pub fn claimable(env: Env, holder: Address, distribution_id: u64) -> i128 {
        let d = read(&env, distribution_id);
        if is_claimed(&env, distribution_id, &holder) || window_closed(&env, &d) {
            return 0;
        }
        share_of(&env, &d, &holder)
    }

    pub fn has_claimed(env: Env, holder: Address, distribution_id: u64) -> bool {
        is_claimed(&env, distribution_id, &holder)
    }

    pub fn distributions_for(env: Env, asset_token: Address) -> Vec<u64> {
        env.storage()
            .persistent()
            .get(&DataKey::ByToken(asset_token))
            .unwrap_or_else(|| Vec::new(&env))
    }

    pub fn distribution_count(env: Env) -> u64 {
        env.storage().instance().get(&DataKey::NextId).unwrap_or(0)
    }
}

fn read(env: &Env, id: u64) -> Distribution {
    env.storage()
        .persistent()
        .get(&DataKey::Distribution(id))
        .unwrap_or_else(|| panic_with_error!(env, DistributorError::DistributionNotFound))
}

fn write(env: &Env, d: &Distribution) {
    let key = DataKey::Distribution(d.id);
    env.storage().persistent().set(&key, d);
    env.storage()
        .persistent()
        .extend_ttl(&key, LIFETIME_THRESHOLD, BUMP_AMOUNT);
}

fn is_claimed(env: &Env, id: u64, holder: &Address) -> bool {
    env.storage()
        .persistent()
        .has(&DataKey::Claimed(id, holder.clone()))
}

fn window_closed(env: &Env, d: &Distribution) -> bool {
    d.reclaimed || (d.claim_deadline != 0 && env.ledger().timestamp() > d.claim_deadline)
}

fn share_of(env: &Env, d: &Distribution, holder: &Address) -> i128 {
    let balance = SnapshotTokenClient::new(env, &d.asset_token).balance_of_at(holder, &d.snapshot_id);
    if balance <= 0 {
        return 0;
    }
    d.total_amount * balance / d.supply_at_snapshot
}

fn claim_one(env: &Env, holder: &Address, id: u64) -> i128 {
    let mut d = read(env, id);
    if is_claimed(env, id, holder) {
        panic_with_error!(env, DistributorError::AlreadyClaimed);
    }
    if window_closed(env, &d) {
        panic_with_error!(env, DistributorError::ClaimWindowClosed);
    }
    let share = share_of(env, &d, holder);
    if share <= 0 {
        panic_with_error!(env, DistributorError::NothingToClaim);
    }
    let key = DataKey::Claimed(id, holder.clone());
    env.storage().persistent().set(&key, &true);
    env.storage()
        .persistent()
        .extend_ttl(&key, LIFETIME_THRESHOLD, BUMP_AMOUNT);
    d.claimed_amount += share;
    write(env, &d);
    token::TokenClient::new(env, &d.payout_token).transfer(
        &env.current_contract_address(),
        holder,
        &share,
    );
    env.events()
        .publish((symbol_short!("claimed"), id, holder.clone()), share);
    share
}
