/**
 * Minimal ABIs for Ankara Chain contracts.
 * Full ABIs are auto-generated in contracts-evm/typechain-types.
 * These minimal ABIs are bundled in the SDK for runtime use.
 */

export const TOKEN_FACTORY_ABI = [
  "function deployFarmlandToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string location, uint256 areaSqMeters, string soilType, string irrigationType, string cropHistory, bytes32 titleDocumentHash, uint256 valuationUSD, string stateRegion, uint256 lastUpdated) metadata) payable returns (address)",
  "function deployCommodityReceiptToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string commodityType, uint256 quantityKg, string gradeClassification, string warehouseId, string warehouseLocation, uint256 depositDate, uint256 expiryDate, bytes32 inspectionReportHash, uint256 valuationUSD, string harvestSeason, uint256 lastUpdated) metadata) payable returns (address)",
  "function deployRealEstateToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string propertyId, string propertyType, string locationAddress, uint256 totalAreaSqMeters, bytes32 titleDocumentHash, uint256 valuationUSD, uint256 rentalYieldBps, string occupancyStatus, address developerAddress, uint256 lastUpdated) metadata) payable returns (address)",
  "function deployInvoiceToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string invoiceNumber, string debtorReference, uint256 faceValueUSD, uint256 discountRateBps, uint256 issuanceDate, uint256 dueDate, bytes32 invoiceDocumentHash, string currency, uint256 lastUpdated) metadata) payable returns (address)",
  "function deployCarbonCreditToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string creditType, string verificationBodyRef, uint256 vintageYear, uint256 quantityCO2e, string projectLocation, string projectType, bytes32 verificationDocHash, uint256 lastUpdated) metadata) payable returns (address)",
  "function deployMiningRightsToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string licenseNumber, string mineralType, string concessionArea, uint256 areaHectares, uint256 licenseExpiry, string issuingAuthority, bytes32 licenseDocumentHash, uint256 royaltyRateBps, uint256 lastUpdated) metadata) payable returns (address)",
  "function registerTemplate(uint8 template, address implementation) external",
  "function totalDeployed() view returns (uint256)",
  "function getDeployerTokens(address deployer) view returns (address[])",
  "function deploymentFee() view returns (uint256)",
  "function implementations(uint8) view returns (address)",
  "event TokenDeployed(uint8 indexed template, address indexed tokenAddress, address indexed deployer, bytes32 assetId, string countryCode, uint256 timestamp)",
] as const;

export const FARMLAND_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function pause() external",
  "function unpause() external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function identityVerifier() view returns (address)",
  "function setStatus(uint8 newStatus) external",
  "function setIdentityVerifier(address verifier) external",
  "function getMetadata() view returns (tuple(string location, uint256 areaSqMeters, string soilType, string irrigationType, string cropHistory, bytes32 titleDocumentHash, uint256 valuationUSD, string stateRegion, uint256 lastUpdated))",
  "function valuationUSD() view returns (uint256)",
  "function areaSqMeters() view returns (uint256)",
  "function metadataVersion() view returns (uint256)",
  "function updateValuation(uint256 newValuationUSD) external",
  "function updateTitleDocument(bytes32 newHash) external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
  "event AssetStatusChanged(uint8 indexed oldStatus, uint8 indexed newStatus, uint256 timestamp)",
] as const;

export const COMMODITY_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function pause() external",
  "function unpause() external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function identityVerifier() view returns (address)",
  "function setStatus(uint8 newStatus) external",
  "function getMetadata() view returns (tuple(string commodityType, uint256 quantityKg, string gradeClassification, string warehouseId, string warehouseLocation, uint256 depositDate, uint256 expiryDate, bytes32 inspectionReportHash, uint256 valuationUSD, string harvestSeason, uint256 lastUpdated))",
  "function commodityType() view returns (string)",
  "function quantityKg() view returns (uint256)",
  "function valuationUSD() view returns (uint256)",
  "function isExpired() view returns (bool)",
  "function metadataVersion() view returns (uint256)",
  "function markExpired() external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
] as const;

export const REAL_ESTATE_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function pause() external",
  "function unpause() external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function setStatus(uint8 newStatus) external",
  "function getMetadata() view returns (tuple(string propertyId, string propertyType, string locationAddress, uint256 totalAreaSqMeters, bytes32 titleDocumentHash, uint256 valuationUSD, uint256 rentalYieldBps, string occupancyStatus, address developerAddress, uint256 lastUpdated))",
  "function valuationUSD() view returns (uint256)",
  "function rentalYieldBps() view returns (uint256)",
  "function occupancyStatus() view returns (string)",
  "function metadataVersion() view returns (uint256)",
  "function totalRentalDistributed() view returns (uint256)",
  "function updateValuation(uint256 newValuationUSD) external",
  "function updateOccupancyStatus(string newStatus) external",
  "function declareRentalDistribution(uint256 amountUSD) external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
  "event RentalDeclared(uint256 amountUSD, uint256 perTokenUSD, uint256 timestamp)",
] as const;

export const INVOICE_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function setStatus(uint8 newStatus) external",
  "function getMetadata() view returns (tuple(string invoiceNumber, string debtorReference, uint256 faceValueUSD, uint256 discountRateBps, uint256 issuanceDate, uint256 dueDate, bytes32 invoiceDocumentHash, string currency, uint256 lastUpdated))",
  "function invoiceStatus() view returns (uint8)",
  "function faceValueUSD() view returns (uint256)",
  "function isOverdue() view returns (bool)",
  "function daysUntilDue() view returns (int256)",
  "function metadataVersion() view returns (uint256)",
  "function markFunded() external",
  "function markRepaid() external",
  "function markDefaulted(string reason) external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
  "event InvoiceStatusChanged(uint8 indexed oldStatus, uint8 indexed newStatus, uint256 timestamp)",
] as const;

export const CARBON_CREDIT_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function setStatus(uint8 newStatus) external",
  "function getMetadata() view returns (tuple(string creditType, string verificationBodyRef, uint256 vintageYear, uint256 quantityCO2e, string projectLocation, string projectType, bytes32 verificationDocHash, uint256 lastUpdated))",
  "function creditType() view returns (string)",
  "function vintageYear() view returns (uint256)",
  "function quantityCO2e() view returns (uint256)",
  "function totalRetired() view returns (uint256)",
  "function totalRetirements() view returns (uint256)",
  "function metadataVersion() view returns (uint256)",
  "function retire(uint256 amount, string beneficiary, string note) external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
  "event CreditsRetired(address indexed retiredBy, uint256 amount, string beneficiary, uint256 retirementIndex, uint256 timestamp)",
] as const;

export const MINING_RIGHTS_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function setStatus(uint8 newStatus) external",
  "function getMetadata() view returns (tuple(string licenseNumber, string mineralType, string concessionArea, uint256 areaHectares, uint256 licenseExpiry, string issuingAuthority, bytes32 licenseDocumentHash, uint256 royaltyRateBps, uint256 lastUpdated))",
  "function mineralType() view returns (string)",
  "function royaltyRateBps() view returns (uint256)",
  "function areaHectares() view returns (uint256)",
  "function isLicenseExpired() view returns (bool)",
  "function daysUntilExpiry() view returns (int256)",
  "function totalRoyaltiesDeclared() view returns (uint256)",
  "function metadataVersion() view returns (uint256)",
  "function renewLicense(uint256 newExpiry) external",
  "function markLicenseExpired() external",
  "function declareRoyalty(uint256 extractionValueUSD) external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
  "event RoyaltyDeclared(uint256 extractionValueUSD, uint256 royaltyAmountUSD, uint256 perTokenUSD, uint256 timestamp)",
] as const;

export const WHITELIST_VERIFIER_ABI = [
  "function isVerified(address account) view returns (bool)",
  "function verifyIdentity(address account) external",
  "function revokeIdentity(address account) external",
  "function batchVerify(address[] accounts) external",
  "function verifierName() view returns (string)",
  "event IdentityVerified(address indexed account, uint256 timestamp)",
  "event IdentityRevoked(address indexed account, uint256 timestamp)",
] as const;
