/**
 * Minimal ABIs for Ankara Chain contracts.
 * Full ABIs are auto-generated in contracts-evm/typechain-types.
 * These minimal ABIs are bundled in the SDK for runtime use.
 */

export const TOKEN_FACTORY_ABI = [
  "function deployFarmlandToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string location, uint256 areaSqMeters, string soilType, string irrigationType, string cropHistory, bytes32 titleDocumentHash, uint256 valuationUSD, string stateRegion, uint256 lastUpdated) metadata) payable returns (address)",
  "function deployCommodityReceiptToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string commodityType, uint256 quantityKg, string gradeClassification, string warehouseId, string warehouseLocation, uint256 depositDate, uint256 expiryDate, bytes32 inspectionReportHash, uint256 valuationUSD, string harvestSeason, uint256 lastUpdated) metadata) payable returns (address)",
  "function deployRealEstateToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string propertyId, string propertyType, string locationAddress, uint256 totalAreaSqMeters, bytes32 titleDocumentHash, uint256 valuationUSD, uint256 rentalYieldBps, string occupancyStatus, address developerAddress, uint256 lastUpdated) metadata) payable returns (address)",
  "function deployInvoiceToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string invoiceNumber, string debtorReference, uint256 faceValueUSD, uint256 discountRateBps, uint256 issuanceDate, uint256 dueDate, bytes32 invoiceDocumentHash, string currency, uint256 lastUpdated) metadata) payable returns (address)",
  "function deployCarbonCreditToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string creditType, string verificationBodyRef, uint256 vintageYear, uint256 quantityCO2e, string projectLocation, string projectType, bytes32 verificationDocHash, uint256 lastUpdated) metadata) payable returns (address)",
  "function deployMiningRightsToken(string name, string symbol, bytes32 assetId, string country, address admin, address verifier, tuple(string licenseNumber, string mineralType, string concessionArea, uint256 areaHectares, uint256 licenseExpiry, string issuingAuthority, bytes32 licenseDocumentHash, uint256 royaltyRateBps, uint256 lastUpdated) metadata) payable returns (address)",
  "function registerTemplate(uint8 template, address implementation) external",
  "function totalDeployed() view returns (uint256)",
  "function getDeployerTokens(address deployer) view returns (address[])",
  "function deploymentFee() view returns (uint256)",
  "function implementations(uint8) view returns (address)",
  "event TokenDeployed(uint8 indexed template, address indexed tokenAddress, address indexed deployer, bytes32 assetId, string countryCode, uint256 timestamp)",
] as const;

export const FARMLAND_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function pause() external",
  "function unpause() external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function identityVerifier() view returns (address)",
  "function setStatus(uint8 newStatus) external",
  "function setIdentityVerifier(address verifier) external",
  "function getMetadata() view returns (tuple(string location, uint256 areaSqMeters, string soilType, string irrigationType, string cropHistory, bytes32 titleDocumentHash, uint256 valuationUSD, string stateRegion, uint256 lastUpdated))",
  "function valuationUSD() view returns (uint256)",
  "function areaSqMeters() view returns (uint256)",
  "function metadataVersion() view returns (uint256)",
  "function updateValuation(uint256 newValuationUSD) external",
  "function updateTitleDocument(bytes32 newHash) external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
  "event AssetStatusChanged(uint8 indexed oldStatus, uint8 indexed newStatus, uint256 timestamp)",
] as const;

export const COMMODITY_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function transfer(address to, uint256 amount) returns (bool)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function pause() external",
  "function unpause() external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function identityVerifier() view returns (address)",
  "function setStatus(uint8 newStatus) external",
  "function getMetadata() view returns (tuple(string commodityType, uint256 quantityKg, string gradeClassification, string warehouseId, string warehouseLocation, uint256 depositDate, uint256 expiryDate, bytes32 inspectionReportHash, uint256 valuationUSD, string harvestSeason, uint256 lastUpdated))",
  "function commodityType() view returns (string)",
  "function quantityKg() view returns (uint256)",
  "function valuationUSD() view returns (uint256)",
  "function isExpired() view returns (bool)",
  "function metadataVersion() view returns (uint256)",
  "function markExpired() external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
] as const;

export const REAL_ESTATE_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function pause() external",
  "function unpause() external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function setStatus(uint8 newStatus) external",
  "function getMetadata() view returns (tuple(string propertyId, string propertyType, string locationAddress, uint256 totalAreaSqMeters, bytes32 titleDocumentHash, uint256 valuationUSD, uint256 rentalYieldBps, string occupancyStatus, address developerAddress, uint256 lastUpdated))",
  "function valuationUSD() view returns (uint256)",
  "function rentalYieldBps() view returns (uint256)",
  "function occupancyStatus() view returns (string)",
  "function metadataVersion() view returns (uint256)",
  "function totalRentalDistributed() view returns (uint256)",
  "function updateValuation(uint256 newValuationUSD) external",
  "function updateOccupancyStatus(string newStatus) external",
  "function declareRentalDistribution(uint256 amountUSD) external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
  "event RentalDeclared(uint256 amountUSD, uint256 perTokenUSD, uint256 timestamp)",
] as const;

export const INVOICE_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function setStatus(uint8 newStatus) external",
  "function getMetadata() view returns (tuple(string invoiceNumber, string debtorReference, uint256 faceValueUSD, uint256 discountRateBps, uint256 issuanceDate, uint256 dueDate, bytes32 invoiceDocumentHash, string currency, uint256 lastUpdated))",
  "function invoiceStatus() view returns (uint8)",
  "function faceValueUSD() view returns (uint256)",
  "function isOverdue() view returns (bool)",
  "function daysUntilDue() view returns (int256)",
  "function metadataVersion() view returns (uint256)",
  "function markFunded() external",
  "function markRepaid() external",
  "function markDefaulted(string reason) external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
  "event InvoiceStatusChanged(uint8 indexed oldStatus, uint8 indexed newStatus, uint256 timestamp)",
] as const;

export const CARBON_CREDIT_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function setStatus(uint8 newStatus) external",
  "function getMetadata() view returns (tuple(string creditType, string verificationBodyRef, uint256 vintageYear, uint256 quantityCO2e, string projectLocation, string projectType, bytes32 verificationDocHash, uint256 lastUpdated))",
  "function creditType() view returns (string)",
  "function vintageYear() view returns (uint256)",
  "function quantityCO2e() view returns (uint256)",
  "function totalRetired() view returns (uint256)",
  "function totalRetirements() view returns (uint256)",
  "function metadataVersion() view returns (uint256)",
  "function retire(uint256 amount, string beneficiary, string note) external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
  "event CreditsRetired(address indexed retiredBy, uint256 amount, string beneficiary, uint256 retirementIndex, uint256 timestamp)",
] as const;

export const MINING_RIGHTS_TOKEN_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function mint(address to, uint256 amount) external",
  "function burn(uint256 amount) external",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function setStatus(uint8 newStatus) external",
  "function getMetadata() view returns (tuple(string licenseNumber, string mineralType, string concessionArea, uint256 areaHectares, uint256 licenseExpiry, string issuingAuthority, bytes32 licenseDocumentHash, uint256 royaltyRateBps, uint256 lastUpdated))",
  "function mineralType() view returns (string)",
  "function royaltyRateBps() view returns (uint256)",
  "function areaHectares() view returns (uint256)",
  "function isLicenseExpired() view returns (bool)",
  "function daysUntilExpiry() view returns (int256)",
  "function totalRoyaltiesDeclared() view returns (uint256)",
  "function metadataVersion() view returns (uint256)",
  "function renewLicense(uint256 newExpiry) external",
  "function markLicenseExpired() external",
  "function declareRoyalty(uint256 extractionValueUSD) external",
  "event Transfer(address indexed from, address indexed to, uint256 value)",
  "event MetadataUpdated(uint256 indexed version, uint256 timestamp)",
  "event RoyaltyDeclared(uint256 extractionValueUSD, uint256 royaltyAmountUSD, uint256 perTokenUSD, uint256 timestamp)",
] as const;

// ─── NFT Factory ABI ─────────────────────────────────────────────────────────

export const NFT_FACTORY_ABI = [
  "function deployFarmlandNFT(string name, string symbol, bytes32 assetId, string country, address admin, address verifier) payable returns (address)",
  "function deployRealEstateNFT(string name, string symbol, bytes32 assetId, string country, address admin, address verifier) payable returns (address)",
  "function deployMiningRightsNFT(string name, string symbol, bytes32 assetId, string country, address admin, address verifier) payable returns (address)",
  "function deployCommodityVaultNFT(string name, string symbol, bytes32 assetId, string country, address admin, address verifier) payable returns (address)",
  "function registerTemplate(uint8 template, address implementation) external",
  "function totalDeployedNFTs() view returns (uint256)",
  "function getDeployerNFTs(address deployer) view returns (address[])",
  "function deploymentFee() view returns (uint256)",
  "function implementations(uint8) view returns (address)",
  "event NFTDeployed(uint8 indexed template, address indexed nftAddress, address indexed deployer, bytes32 assetId, string countryCode, uint256 timestamp)",
] as const;

// ─── NFT Template ABIs ───────────────────────────────────────────────────────

export const FARMLAND_NFT_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function balanceOf(address owner) view returns (uint256)",
  "function transferFrom(address from, address to, uint256 tokenId) external",
  "function safeTransferFrom(address from, address to, uint256 tokenId) external",
  "function approve(address to, uint256 tokenId) external",
  "function setApprovalForAll(address operator, bool approved) external",
  "function burn(uint256 tokenId) external",
  "function mint(address to, tuple(string location, uint256 areaSqMeters, string soilType, string irrigationType, string cropHistory, bytes32 titleDocumentHash, bytes32 surveyReportHash, string stateRegion, uint256 lastUpdated) meta) external returns (uint256)",
  "function getMetadata(uint256 tokenId) view returns (tuple(string location, uint256 areaSqMeters, string soilType, string irrigationType, string cropHistory, bytes32 titleDocumentHash, bytes32 surveyReportHash, string stateRegion, uint256 lastUpdated))",
  "function updateMetadata(uint256 tokenId, tuple(string location, uint256 areaSqMeters, string soilType, string irrigationType, string cropHistory, bytes32 titleDocumentHash, bytes32 surveyReportHash, string stateRegion, uint256 lastUpdated) meta) external",
  "function updateTitleDocument(uint256 tokenId, bytes32 newHash) external",
  "function metadataVersion(uint256 tokenId) view returns (uint256)",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function identityVerifier() view returns (address)",
  "function linkedERC20() view returns (address)",
  "function setStatus(uint8 newStatus) external",
  "function setIdentityVerifier(address verifier) external",
  "function linkToERC20(address erc20Address) external",
  "function pause() external",
  "function unpause() external",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event FarmlandNFTMinted(uint256 indexed tokenId, address indexed to, bytes32 assetId)",
  "event MetadataUpdated(uint256 indexed tokenId, uint256 version, uint256 timestamp)",
  "event ERC20Linked(address indexed erc20Address)",
] as const;

export const REAL_ESTATE_NFT_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function balanceOf(address owner) view returns (uint256)",
  "function transferFrom(address from, address to, uint256 tokenId) external",
  "function safeTransferFrom(address from, address to, uint256 tokenId) external",
  "function burn(uint256 tokenId) external",
  "function mint(address to, tuple(string propertyId, string propertyType, string locationAddress, uint256 totalAreaSqMeters, bytes32 titleDocumentHash, uint256 valuationUSD, uint256 rentalYieldBps, address developerAddress, uint256 lastUpdated) meta) external returns (uint256)",
  "function getMetadata(uint256 tokenId) view returns (tuple(string propertyId, string propertyType, string locationAddress, uint256 totalAreaSqMeters, bytes32 titleDocumentHash, uint256 valuationUSD, uint256 rentalYieldBps, address developerAddress, uint256 lastUpdated))",
  "function updateMetadata(uint256 tokenId, tuple(string propertyId, string propertyType, string locationAddress, uint256 totalAreaSqMeters, bytes32 titleDocumentHash, uint256 valuationUSD, uint256 rentalYieldBps, address developerAddress, uint256 lastUpdated) meta) external",
  "function updateValuation(uint256 tokenId, uint256 newValuationUSD) external",
  "function metadataVersion(uint256 tokenId) view returns (uint256)",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function linkedERC20() view returns (address)",
  "function setStatus(uint8 newStatus) external",
  "function linkToERC20(address erc20Address) external",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event RealEstateNFTMinted(uint256 indexed tokenId, address indexed to, bytes32 assetId)",
  "event MetadataUpdated(uint256 indexed tokenId, uint256 version, uint256 timestamp)",
  "event ValuationUpdated(uint256 indexed tokenId, uint256 oldValue, uint256 newValue, uint256 timestamp)",
  "event ERC20Linked(address indexed erc20Address)",
] as const;

export const MINING_RIGHTS_NFT_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function balanceOf(address owner) view returns (uint256)",
  "function transferFrom(address from, address to, uint256 tokenId) external",
  "function burn(uint256 tokenId) external",
  "function mint(address to, tuple(string licenseNumber, string mineralType, string concessionArea, uint256 areaHectares, uint256 licenseExpiry, string issuingAuthority, bytes32 licenseDocumentHash, uint256 royaltyRateBps, uint256 lastUpdated) meta) external returns (uint256)",
  "function getMetadata(uint256 tokenId) view returns (tuple(string licenseNumber, string mineralType, string concessionArea, uint256 areaHectares, uint256 licenseExpiry, string issuingAuthority, bytes32 licenseDocumentHash, uint256 royaltyRateBps, uint256 lastUpdated))",
  "function updateMetadata(uint256 tokenId, tuple(string licenseNumber, string mineralType, string concessionArea, uint256 areaHectares, uint256 licenseExpiry, string issuingAuthority, bytes32 licenseDocumentHash, uint256 royaltyRateBps, uint256 lastUpdated) meta) external",
  "function renewLicense(uint256 tokenId, uint256 newExpiry) external",
  "function isLicenseExpired(uint256 tokenId) view returns (bool)",
  "function metadataVersion(uint256 tokenId) view returns (uint256)",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function linkedERC20() view returns (address)",
  "function setStatus(uint8 newStatus) external",
  "function linkToERC20(address erc20Address) external",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event MiningRightsNFTMinted(uint256 indexed tokenId, address indexed to, bytes32 assetId)",
  "event MetadataUpdated(uint256 indexed tokenId, uint256 version, uint256 timestamp)",
  "event LicenseRenewed(uint256 indexed tokenId, uint256 oldExpiry, uint256 newExpiry)",
  "event ERC20Linked(address indexed erc20Address)",
] as const;

export const COMMODITY_VAULT_NFT_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function balanceOf(address owner) view returns (uint256)",
  "function transferFrom(address from, address to, uint256 tokenId) external",
  "function burn(uint256 tokenId) external",
  "function mint(address to, tuple(string warehouseId, string warehouseLocation, address operatorAddress, string commodityType, uint256 quantityKg, string gradeClassification, bytes32 certificateHash, uint256 depositDate, uint256 lastUpdated) meta) external returns (uint256)",
  "function getMetadata(uint256 tokenId) view returns (tuple(string warehouseId, string warehouseLocation, address operatorAddress, string commodityType, uint256 quantityKg, string gradeClassification, bytes32 certificateHash, uint256 depositDate, uint256 lastUpdated))",
  "function updateMetadata(uint256 tokenId, tuple(string warehouseId, string warehouseLocation, address operatorAddress, string commodityType, uint256 quantityKg, string gradeClassification, bytes32 certificateHash, uint256 depositDate, uint256 lastUpdated) meta) external",
  "function metadataVersion(uint256 tokenId) view returns (uint256)",
  "function assetId() view returns (bytes32)",
  "function countryCode() view returns (string)",
  "function status() view returns (uint8)",
  "function linkedERC20() view returns (address)",
  "function setStatus(uint8 newStatus) external",
  "function linkToERC20(address erc20Address) external",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event CommodityVaultNFTMinted(uint256 indexed tokenId, address indexed to, bytes32 assetId)",
  "event MetadataUpdated(uint256 indexed tokenId, uint256 version, uint256 timestamp)",
  "event ERC20Linked(address indexed erc20Address)",
] as const;

export const WHITELIST_VERIFIER_ABI = [
  "function isVerified(address account) view returns (bool)",
  "function verifyIdentity(address account) external",
  "function revokeIdentity(address account) external",
  "function batchVerify(address[] accounts) external",
  "function verifierName() view returns (string)",
  "event IdentityVerified(address indexed account, uint256 timestamp)",
  "event IdentityRevoked(address indexed account, uint256 timestamp)",
] as const;

export const MULTI_TOKEN_FACTORY_ABI = [
  "function deployCommodityBatchToken(string name_, string countryCode_, string baseURI_, address admin_, tuple(string warehouseId, string warehouseLocation, address operatorAddress, bytes32 warehouseLicenseHash, uint256 certificationExpiry) warehouse_) payable returns (address)",
  "function deployPoolVault(string name_, string symbol_, bytes32 assetId_, string countryCode_, address admin_, address verifier_, address oracle_, uint256 managementFeeBps_) payable returns (address)",
  "function registerTemplate(uint8 template, address implementation) external",
  "function totalDeployedMultiTokens() view returns (uint256)",
  "function getDeployerMultiTokens(address deployer) view returns (address[])",
  "function deploymentFee() view returns (uint256)",
  "event MultiTokenDeployed(uint8 indexed template, address indexed contractAddress, address indexed deployer, bytes32 assetId, string countryCode, uint256 timestamp)",
] as const;

export const COMMODITY_BATCH_TOKEN_ABI = [
  "function contractName() view returns (string)",
  "function contractCountryCode() view returns (string)",
  "function registerBatch(uint256 id, tuple(string commodityType, uint256 quantityKg, string gradeClassification, uint256 depositDate, uint256 expiryDate, bytes32 inspectionReportHash, uint256 valuationUSD, string harvestSeason, string originCountry) meta) external",
  "function mint(address to, uint256 id, uint256 amount, bytes data) external",
  "function balanceOf(address account, uint256 id) view returns (uint256)",
  "function getBatchMetadata(uint256 id) view returns (tuple(string commodityType, uint256 quantityKg, string gradeClassification, uint256 depositDate, uint256 expiryDate, bytes32 inspectionReportHash, uint256 valuationUSD, string harvestSeason, string originCountry))",
  "function getWarehouseMetadata() view returns (tuple(string warehouseId, string warehouseLocation, address operatorAddress, bytes32 warehouseLicenseHash, uint256 certificationExpiry))",
  "function activeBatchCount() view returns (uint256)",
  "function batchIds(uint256 index) view returns (uint256)",
  "function isExpired(uint256 id) view returns (bool)",
  "function expireBatch(uint256 id) external",
  "event BatchRegistered(uint256 indexed id, string commodityType, uint256 quantityKg)",
] as const;

export const POOL_VAULT_ABI = [
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function totalSupply() view returns (uint256)",
  "function balanceOf(address) view returns (uint256)",
  "function deposit(address tokenAddress, uint256 amount) external",
  "function withdraw(uint256 poolTokenAmount) external",
  "function accrueManagementFee() external",
  "function NAVPerToken() view returns (uint256)",
  "function totalAUM() view returns (uint256)",
  "function acceptedTokens() view returns (address[])",
  "function addAcceptedToken(address token, uint256 weightBps) external",
  "function removeAcceptedToken(address token) external",
  "function setOracle(address oracle_) external",
  "function setManagementFeeBps(uint256 newFeeBps) external",
  "function managementFeeBps() view returns (uint256)",
  "function oracle() view returns (address)",
  "function lastFeeAccrual() view returns (uint256)",
  "function isAccepted(address token) view returns (bool)",
  "event Deposited(address indexed investor, address indexed token, uint256 amount, uint256 poolTokensMinted)",
  "event Withdrawn(address indexed investor, uint256 poolTokensBurned, address[] tokens, uint256[] amounts)",
  "event FeeAccrued(uint256 feeTokens, uint256 timestamp)",
] as const;

// ─── Escrow Factory + MilestoneEscrow ────────────────────────────────────────

export const ESCROW_FACTORY_ABI = [
  "function deployEscrow(address admin_, address payer_, address payee_, address arbiter_, address token_, address identityVerifier_, uint256 timelockDuration_, uint256[] amounts_, bytes32[] descriptionHashes_) payable returns (address)",
  "function setImplementation(address newImplementation) external",
  "function setStablecoinAccepted(address token, bool accepted) external",
  "function acceptedStablecoins(address) view returns (bool)",
  "function implementation() view returns (address)",
  "function totalDeployedEscrows() view returns (uint256)",
  "function getDeployerEscrows(address deployer) view returns (address[])",
  "function deploymentFee() view returns (uint256)",
  "event EscrowDeployed(address indexed escrowAddress, address indexed deployer, address payer, address payee, address token, uint256 totalAmount, uint256 timestamp)",
] as const;

export const MILESTONE_ESCROW_ABI = [
  "function payer() view returns (address)",
  "function payee() view returns (address)",
  "function arbiter() view returns (address)",
  "function token() view returns (address)",
  "function identityVerifier() view returns (address)",
  "function timelockDuration() view returns (uint256)",
  "function totalAmount() view returns (uint256)",
  "function funded() view returns (bool)",
  "function cancelled() view returns (bool)",
  "function fund() external",
  "function markDelivered(uint256 milestoneId) external",
  "function approveMilestone(uint256 milestoneId) external",
  "function raiseDispute(uint256 milestoneId) external",
  "function resolveDispute(uint256 milestoneId, bool releaseToPayee) external",
  "function claimTimelockRelease(uint256 milestoneId) external",
  "function voteCancel() external",
  "function setArbiter(address newArbiter) external",
  "function setIdentityVerifier(address verifier) external",
  "function pause() external",
  "function unpause() external",
  "function milestoneCount() view returns (uint256)",
  "function getMilestone(uint256 milestoneId) view returns (tuple(uint256 amount, bytes32 descriptionHash, uint8 status, uint256 deliveredAt))",
  "function remainingBalance() view returns (uint256)",
  "event EscrowFunded(uint256 totalAmount)",
  "event MilestoneDelivered(uint256 indexed id, uint256 timestamp)",
  "event MilestoneReleased(uint256 indexed id, uint256 amount, bool viaTimelock)",
  "event MilestoneDisputed(uint256 indexed id, address indexed raisedBy)",
  "event DisputeResolved(uint256 indexed id, bool releasedToPayee)",
  "event MilestoneRefunded(uint256 indexed id, uint256 amount)",
  "event EscrowCancelled(uint256 refundedAmount)",
] as const;

export const MANUAL_ORACLE_ABI = [
  "function getPrice(address tokenAddress) view returns (uint256 priceUSD, uint256 timestamp)",
  "function isStale(address tokenAddress) view returns (bool)",
  "function setPrice(address token, uint256 priceUSD) external",
  "function setStalenessThreshold(uint256 newThreshold) external",
  "function stalenessThreshold() view returns (uint256)",
  "event PriceSet(address indexed token, uint256 priceUSD, uint256 timestamp)",
] as const;
